### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by Asmaa-ezz** [FACG5/CHariZone#2]
Relates #1 
 
# Persona I:
  ## As a user
  - [ ] I can visit charizone.com to search for sectors/causes to give to (Videos/ or slides).
  - [ ] I can filter by income, KPI.
  - [ ]  I can scroll down a list of charities within that sector (the list will include a 1-line description of what 
         the charity does). 
  - [ ] I can select a charity to view information about the charity (standard Charity Commission Data eg 
   Charity Base).
  - [ ] I can select up to 3 charities from the list of charities and click a button to show a comparison page 
  (KPIs) of the selected charities.
  - [ ]  I can contact the charity anonymously and ask additional questions (pre-selected)
  - [ ]  I can donate to the charity I selected. 

---

# Persona II:
  ## As a user
  - [ ]  I can visit charizone.com to search for the charity I give to.
  - [ ] I can select a charity to view information about the charity (standard Charity Commission Data eg Charity Base).
  - [ ] I can select up to 3 charities from the list of charities and click a button to show a comparison page 
  (KPIs) of the selected charities.
  - [ ]  I can contact the charity anonymously and ask additional questions (pre-selected).
  - [ ]  I can also browse the website to learn more about the cause and investigate other
